version: '3.8'

services:
  jongubooks:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
      - ./static:/app/static
    restart: unless-stopped 